/**
 * portalInstituteConfig.js
 *
 * Per-institute-type terminology map for the three portals
 * (Student, Parent, Teacher).
 *
 * Usage:
 *   import { getPortalTerms } from '@/constants/portalInstituteConfig';
 *   const t = getPortalTerms(portalUser?.institute_type);
 *   // then: t.classLabel, t.subjectLabel, t.nav.classes, …
 */

const CONFIG = {
  // ── SCHOOL ───────────────────────────────────────────────
  school: {
    classLabel:         'Class',
    classesLabel:       'Classes',
    batchLabel:         'Section',
    subjectLabel:       'Subject',
    subjectsLabel:      'Subjects',
    rollLabel:          'Roll No.',
    examLabel:          'Exam',
    examsLabel:         'Exams',
    timetableLabel:     'Timetable',
    syllabusLabel:      'Syllabus',
    teacherLabel:       'Teacher',
    instructorLabel:    'Teacher',
    studentLabel:       'Student',
    studentsLabel:      'Students',
    feeLabel:           'Fee',
    feesLabel:          'Fees',
    assignmentLabel:    'Assignment',
    assignmentsLabel:   'Assignments',
    homeworkLabel:      'Homework Diary',
    notesLabel:         'Notes',
    marksLabel:         'Marks',
    gradeLabel:         'Grade',
    resultLabel:        'Result',
    resultsLabel:       'Exam Results',
    attendanceLabel:    'Attendance',
    announcementsLabel: 'Announcements',
    overviewLabel:      'Overview',
    nav: {
      overview:    'Overview',
      classes:     'My Classes',
      students:    'My Students',
      notes:       'Notes',
      assignments: 'Assignments',
      homework:    'Homework & Diary',
      attendance:  'Mark Attendance',
      myAttend:    'My Attendance',
      timetable:   'Timetable',
      syllabus:    'Syllabus',
      exams:       'My Exams',
      fees:        'My Fees',
      results:     'Exam Results',
      announcements: 'Announcements',
    },
  },

  // ── COACHING CENTER ───────────────────────────────────────
  coaching: {
    classLabel:         'Batch',
    classesLabel:       'Batches',
    batchLabel:         'Group',
    subjectLabel:       'Course',
    subjectsLabel:      'Courses',
    rollLabel:          'Reg. No.',
    examLabel:          'Test',
    examsLabel:         'Tests',
    timetableLabel:     'Schedule',
    syllabusLabel:      'Course Outline',
    teacherLabel:       'Instructor',
    instructorLabel:    'Instructor',
    studentLabel:       'Student',
    studentsLabel:      'Students',
    feeLabel:           'Fee',
    feesLabel:          'Fees',
    assignmentLabel:    'Practice Set',
    assignmentsLabel:   'Practice Sets',
    homeworkLabel:      'Daily Tasks',
    notesLabel:         'Study Material',
    marksLabel:         'Marks',
    gradeLabel:         'Grade',
    resultLabel:        'Result',
    resultsLabel:       'Test Results',
    attendanceLabel:    'Attendance',
    announcementsLabel: 'Announcements',
    overviewLabel:      'Overview',
    nav: {
      overview:    'Overview',
      classes:     'My Batches',
      students:    'My Students',
      notes:       'Study Material',
      assignments: 'Practice Sets',
      homework:    'Daily Tasks',
      attendance:  'Mark Attendance',
      myAttend:    'My Attendance',
      timetable:   'Schedule',
      syllabus:    'Course Outline',
      exams:       'My Tests',
      fees:        'My Fees',
      results:     'Test Results',
      announcements: 'Announcements',
    },
  },

  // ── ACADEMY ──────────────────────────────────────────────
  academy: {
    classLabel:         'Batch',
    classesLabel:       'Batches',
    batchLabel:         'Group',
    subjectLabel:       'Course',
    subjectsLabel:      'Courses',
    rollLabel:          'Student ID',
    examLabel:          'Assessment',
    examsLabel:         'Assessments',
    timetableLabel:     'Schedule',
    syllabusLabel:      'Course Outline',
    teacherLabel:       'Instructor',
    instructorLabel:    'Instructor',
    studentLabel:       'Trainee',
    studentsLabel:      'Trainees',
    feeLabel:           'Fee',
    feesLabel:          'Fees',
    assignmentLabel:    'Assignment',
    assignmentsLabel:   'Assignments',
    homeworkLabel:      'Practice Tasks',
    notesLabel:         'Course Material',
    marksLabel:         'Score',
    gradeLabel:         'Grade',
    resultLabel:        'Result',
    resultsLabel:       'Assessment Results',
    attendanceLabel:    'Attendance',
    announcementsLabel: 'Announcements',
    overviewLabel:      'Overview',
    nav: {
      overview:    'Overview',
      classes:     'My Batches',
      students:    'My Trainees',
      notes:       'Course Material',
      assignments: 'Assignments',
      homework:    'Practice Tasks',
      attendance:  'Mark Attendance',
      myAttend:    'My Attendance',
      timetable:   'Schedule',
      syllabus:    'Course Outline',
      exams:       'My Assessments',
      fees:        'My Fees',
      results:     'Assessment Results',
      announcements: 'Announcements',
    },
  },

  // ── COLLEGE ──────────────────────────────────────────────
  college: {
    classLabel:         'Class',
    classesLabel:       'Classes',
    batchLabel:         'Section',
    subjectLabel:       'Subject',
    subjectsLabel:      'Subjects',
    rollLabel:          'Roll No.',
    examLabel:          'Exam',
    examsLabel:         'Exams',
    timetableLabel:     'Timetable',
    syllabusLabel:      'Syllabus',
    teacherLabel:       'Lecturer',
    instructorLabel:    'Lecturer',
    studentLabel:       'Student',
    studentsLabel:      'Students',
    feeLabel:           'Fee',
    feesLabel:          'Fees',
    assignmentLabel:    'Assignment',
    assignmentsLabel:   'Assignments',
    homeworkLabel:      'Tasks & Diary',
    notesLabel:         'Lecture Notes',
    marksLabel:         'Marks',
    gradeLabel:         'Grade',
    resultLabel:        'Result',
    resultsLabel:       'Exam Results',
    attendanceLabel:    'Attendance',
    announcementsLabel: 'Announcements',
    overviewLabel:      'Overview',
    nav: {
      overview:    'Overview',
      classes:     'My Classes',
      students:    'My Students',
      notes:       'Lecture Notes',
      assignments: 'Assignments',
      homework:    'Tasks & Diary',
      attendance:  'Mark Attendance',
      myAttend:    'My Attendance',
      timetable:   'Timetable',
      syllabus:    'Syllabus',
      exams:       'My Exams',
      fees:        'My Fees',
      results:     'Exam Results',
      announcements: 'Announcements',
    },
  },

  // ── UNIVERSITY ───────────────────────────────────────────
  university: {
    classLabel:         'Program',
    classesLabel:       'Courses',
    batchLabel:         'Section',
    subjectLabel:       'Course',
    subjectsLabel:      'Courses',
    rollLabel:          'Student ID',
    examLabel:          'Exam',
    examsLabel:         'Exams',
    timetableLabel:     'Schedule',
    syllabusLabel:      'Course Outline',
    teacherLabel:       'Professor',
    instructorLabel:    'Professor',
    studentLabel:       'Student',
    studentsLabel:      'Students',
    feeLabel:           'Tuition Fee',
    feesLabel:          'Tuition Fees',
    assignmentLabel:    'Assignment',
    assignmentsLabel:   'Assignments',
    homeworkLabel:      'Tasks',
    notesLabel:         'Lecture Notes',
    marksLabel:         'Marks',
    gradeLabel:         'GPA',
    resultLabel:        'Result',
    resultsLabel:       'Academic Results',
    attendanceLabel:    'Attendance',
    announcementsLabel: 'Announcements',
    overviewLabel:      'Dashboard',
    nav: {
      overview:    'Dashboard',
      classes:     'My Courses',
      students:    'My Students',
      notes:       'Lecture Notes',
      assignments: 'Assignments',
      homework:    'Tasks',
      attendance:  'Mark Attendance',
      myAttend:    'My Attendance',
      timetable:   'Schedule',
      syllabus:    'Course Outline',
      exams:       'My Exams',
      fees:        'My Fees',
      results:     'Academic Results',
      announcements: 'Notices',
    },
  },
};

/**
 * Returns the terminology config for a given institute type.
 * Falls back to 'school' if no match found.
 *
 * @param {string} instituteType  'school' | 'coaching' | 'academy' | 'college' | 'university'
 */
export function getPortalTerms(instituteType) {
  return CONFIG[instituteType] || CONFIG.school;
}

export default CONFIG;
